version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - frontend_data:/usr/share/nginx/html

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443" # Update this line to expose the 443 port
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend_data:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
volumes:
  postgres_data:
  frontend_data:
  cert_data: # Add this volume to store the certificates

