version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8086:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
